// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Testing

@testable import Fuzzilli

struct ContextGraphTests {
    @Test
    func testReachabilityCalculationForJS() {
        let fuzzer = makeMockFuzzer()
        fuzzer.sync {
            let contextGraph = ContextGraph(
                for: fuzzer.codeGenerators, isBundle: false, withLogger: Logger(withLabel: "Test"))

            let reachableContexts = Set(contextGraph.getReachableContexts(from: .javascript))

            let reachableContexts2 = Set(contextGraph.getReachableContexts(from: .javascript))

            #expect(reachableContexts == reachableContexts2)

            var expectedReachedContexts = Set(Context.allCases)
            expectedReachedContexts.remove(.empty)
            // Only reachable in the "bundle" configuration.
            expectedReachedContexts.remove(.bundle)
            expectedReachedContexts.remove(.moduleTopLevel)

            // Only generated by a specific code generator
            expectedReachedContexts.remove(.workerFunction)

            #expect(reachableContexts == expectedReachedContexts)
        }
    }

    @Test
    func testReachabilityCalculationForBundles() {
        let config = Configuration(logLevel: .error, generateBundle: true)
        let fuzzer = makeMockFuzzer(config: config)
        fuzzer.sync {
            let contextGraph = ContextGraph(
                for: fuzzer.codeGenerators, isBundle: true, withLogger: Logger(withLabel: "Test"))

            let reachableContexts = Set(contextGraph.getReachableContexts(from: .bundle))

            let reachableContexts2 = Set(contextGraph.getReachableContexts(from: .bundle))

            #expect(reachableContexts == reachableContexts2)

            var expectedReachedContexts = Set(Context.allCases)
            expectedReachedContexts.remove(.empty)

            // Only generated by a specific code generator
            expectedReachedContexts.remove(.workerFunction)

            #expect(reachableContexts == expectedReachedContexts)
        }
    }

    @Test
    func testSubsetReachabilityCalculation() {
        let fuzzer = makeMockFuzzer()
        fuzzer.sync {
            let contextGraph = ContextGraph(
                for: fuzzer.codeGenerators, isBundle: false, withLogger: Logger(withLabel: "Test"))
            let reachableContextsWasm = Set(contextGraph.getReachableContexts(from: .wasm))
            let reachableContextsWasm2 = Set(contextGraph.getReachableContexts(from: .wasm))

            #expect(reachableContextsWasm == reachableContextsWasm2)

            let reachableContextsWasmFunction = Set(
                contextGraph.getReachableContexts(from: .wasmFunction))
            let reachableContextsJavaScript = Set(
                contextGraph.getReachableContexts(from: .javascript))

            #expect(reachableContextsWasmFunction.isSubset(of: reachableContextsWasm))
            #expect(
                reachableContextsWasm
                    == Set([
                        .wasmFunction,
                        .wasm,
                    ]))
            #expect(reachableContextsWasm.isSubset(of: reachableContextsJavaScript))
        }
    }
}
