from smolagents import tool
from common_tools import *
from rag_tools import * # deal with this later

@tool
def tree(directory: str = ".", options: str = "") -> str:
    """
    Display directory structure using tree command to explore project layout.
    
    Args:
        directory (str, optional): The directory to explore. Defaults to current directory ".".
        options (str, optional): Additional tree command options. Common options include:
            -L NUM: Limit depth to NUM levels
            -f: Show full path prefix 
    
    Returns:
        str: Tree structure showing directories and files in the specified path.
    """
    return run_command(f"tree {options} {directory}")

@tool 
def run_d8(target: str, options: str = "") -> str:
    """
    Run the target program using d8 to test for syntactical correctness
    and test for coverage. 

    Args:
        --print-maglev-code (print maglev code)
        --trace-maglev-graph-building (trace maglev graph building)
        --print-maglev-graph (print the final maglev graph)
        --print-maglev-graphs (print maglev graph across all phases)
        --maglev-stats (print Maglev statistics)
        --jit-fuzzing (Set JIT tiering thresholds suitable for JIT fuzzing)
        --print-bytecode (print bytecode generated by ignition interpreter)
        --trace-turbo (trace generated TurboFan IR)
        --trace-turbo-path (directory to dump generated TurboFan IR to) 
            Ex: --trace-turbo-path=/tmp/turbofan_ir
        --trace-turbo-graph (trace generated TurboFan graphs)
        --turbo-stats (print TurboFan statistics)
        --trace-wasm-compiler (trace compiling of wasm code)
        --trace-wasm (trace wasm function calls)

        ```
        TODO: Trace output destination of each of the above flags. 
              Regardless of whether it is printed to stdout or to
              a file, I will want to put it in a predetermined
              place that an AI can easily parse in digestible chunks.
        ```

        AT ANY POINT IN TIME YOU CAN ONLY PICK UP TO 4 OF THESE OPTIONS.
    """ 
    return run_command(f"/usr/share/vrigatoni/fuzzillai/v8/v8/out/fuzzbuild/d8 {target} {options}")

# TODO: @Tanush - good luck
@tool
def get_call_graph(target: str) -> str:
    """
    Get the call graph of the target program using d8 to test for syntactical correctness
    and test for coverage. 
    """
    return run_command(f"")  # Database access wrappere

