#!/bin/bash
for filename in *.js; do
    newFilename="${filename/.js/.swift}"
    echo "Converting $filename to $newFilename"
    echo -e "// DO NOT EDIT!\n// Generated by $(basename -- "$0")" > $newFilename
    cat LICENSE >> $newFilename
    echo -e "public let ${filename/.js/}Script = \"\"\"\n$(grep -v '^//' $filename)\n\"\"\"" >> $newFilename
done
